public enum SystemError {
    OK,
    UNKNOWN,
    USER_NOT_EXISTS,
    USER_INVALID_CREDENTIALS,
    USER_NOT_LOGGED_IN,
    USER_ALREADY_LOGGED_IN,
    INVALID_OPERATION_AMOUNT,
    INVALID_OPERATION_AMOUNT_MAX_OVERFLOW,
    INVALID_OPERATION_AMOUNT_MIN_OVERFLOW,
    INVALID_OPERATION_AMOUNT_NO_FUNDS,
    SESSION_NUMBER_OF_OPERATIONS_EXCEEDED
}
